

x={'doctype': 'DocField', 'name': 'af446ff7e7', '_default_new_docs': {}, 'flags': {}, 'creation': datetime.datetime(2013, 2, 22, 1, 28, 2), 'modified': datetime.datetime(2023, 5, 16, 13, 49, 29, 386246), 'modified_by': 'Administrator', 'owner': 'Administrator', 'docstatus': 0, 'parent': 'Landed Cost Item', 'parentfield': 'fields', 'parenttype': 'DocType', 'idx': 3, 'fieldname': 'receipt_document_type', 'label': 'Receipt Document Type', 'oldfieldname': None, 'fieldtype': 'Select', 'oldfieldtype': None, 'options': 'Purchase Invoice\nPurchase Receipt', 'search_index': 0, 'hidden': 0, 'set_only_once': 0, 'allow_in_quick_entry': 0, 'print_hide': 1, 'report_hide': 0, 'reqd': 0, 'bold': 0, 'in_global_search': 0, 'collapsible': 0, 'unique': 0, 'no_copy': 1, 'allow_on_submit': 0, 'show_preview_popup': 0, 'trigger': None, 'collapsible_depends_on': None, 'mandatory_depends_on': None, 'read_only_depends_on': None, 'depends_on': None, 'permlevel': 0, 'ignore_user_permissions': 0, 'width': None, 'print_width': None, 'columns': 0, 'default': None, 'description': None, 'in_list_view': 0, 'fetch_if_empty': 0, 'in_filter': 0, 'remember_last_selected_value': 0, 'ignore_xss_filter': 0, 'print_hide_if_no_value': 0, 'allow_bulk_edit': 0, 'in_standard_filter': 0, 'in_preview': 0, 'read_only': 1, 'precision': None, 'length': 0, 'translatable': 0, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'non_negative': 0, 'fetch_from': None, 'dont_update_if_missing': [], 'parent_doc': <Meta: Landed Cost Item>, '_meta': <Meta: DocField>}






y = {'doctype': 'Stock Entry Detail', 'name': '238598f722', '_default_new_docs': {}, 'flags': {}, 'creation': datetime.datetime(2023, 7, 24, 6, 59, 35, 770056), 'modified': datetime.datetime(2023, 7, 24, 6, 59, 42, 638004), 'modified_by': 'Administrator', 'owner': 'Administrator', 'docstatus': 1, 'parent': 'MAT-STE-2023-00014', 'parentfield': 'items', 'parenttype': 'Stock Entry', 'idx': 1, 'barcode': None, 's_warehouse': 'المخزن الرئيسى الإسكندرية - M.D', 't_warehouse': 'سامر ابراهيم صدقى نجيب - M.D', 'item_code': 'STO-ITEM-2023-00020', 'item_name': 'shesha2', 'is_finished_item': 0, 'is_scrap_item': 0, 'is_process_loss': 0, 'quality_inspection': None, 'subcontracted_item': None, 'description': 'shesha1', 'item_group': 'شيشة (test)', 'image': None, 'qty': 1.0, 'transfer_qty': 1.0, 'retain_sample': 0, 'uom': 'قطعة', 'stock_uom': 'قطعة', 'conversion_factor': 1.0, 'sample_quantity': 0, 'basic_rate': 130.0, 'additional_cost': 0.0, 'valuation_rate': 100.0, 'allow_zero_valuation_rate': 0, 'set_basic_rate_manually': 0, 'basic_amount': 100.0, 'amount': 100.0, 'serial_no': None, 'batch_no': None, 'expense_account': '440001 - تسوية  مخزون - M.D', 'cost_center': 'Main - M.D', 'project': None, 'actual_qty': 1.0, 'transferred_qty': 0.0, 'bom_no': None, 'allow_alternative_item': 0, 'material_request': None, 'material_request_item': None, 'original_item': None, 'against_stock_entry': None, 'ste_detail': None, 'po_detail': None, 'putaway_rule': None, 'reference_purchase_receipt': None, 'job_card_item': None, 'dont_update_if_missing': [], '_meta': <Meta: Stock Entry Detail>, 'parent_doc': <StockEntry: MAT-STE-2023-00014 docstatus=1>, 'rm_supp_cost': 0.0}


slw =[{'item_code': 'STO-ITEM-2023-00020', 'warehouse': 'المخزن الرئيسى الإسكندرية - M.D', 'posting_date': datetime.date(2023, 7, 24), 'posting_time': datetime.timedelta(seconds=25182, microseconds=908388), 'fiscal_year': '2023', 'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2023-00014', 'voucher_detail_no': '238598f722', 'actual_qty': -1.0, 'stock_uom': 'قطعة', 'incoming_rate': 0, 'company': 'Master Deals', 'batch_no': '', 'serial_no': None, 'project': None, 'is_cancelled': 0, 'dependant_sle_voucher_detail_no': '238598f722'}, {'item_code': 'STO-ITEM-2023-00020', 'warehouse': 'سامر ابراهيم صدقى نجيب - M.D', 'posting_date': datetime.date(2023, 7, 24), 'posting_time': datetime.timedelta(seconds=25182, microseconds=908388), 'fiscal_year': '2023', 'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2023-00014', 'voucher_detail_no': '238598f722', 'actual_qty': 1.0, 'stock_uom': 'قطعة', 'incoming_rate': 100.0, 'company': 'Master Deals', 'batch_no': '', 'serial_no': None, 'project': None, 'is_cancelled': 0, 'recalculate_rate': 1}]

[{'item_code': 'STO-ITEM-2023-00020', 'warehouse': 'سامر ابراهيم صدقى نجيب - M.D', 'posting_date': datetime.date(2023, 7, 24), 'posting_time': datetime.timedelta(seconds=25182, microseconds=908388), 'fiscal_year': '2023', 'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2023-00014', 'voucher_detail_no': '238598f722', 'actual_qty': 1.0, 'stock_uom': 'قطعة', 'incoming_rate': 100.0, 'company': 'Master Deals', 'batch_no': '', 'serial_no': None, 'project': None, 'is_cancelled': 1, 'recalculate_rate': 1}, {'item_code': 'STO-ITEM-2023-00020', 'warehouse': 'المخزن الرئيسى الإسكندرية - M.D', 'posting_date': datetime.date(2023, 7, 24), 'posting_time': datetime.timedelta(seconds=25182, microseconds=908388), 'fiscal_year': '2023', 'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2023-00014', 'voucher_detail_no': '238598f722', 'actual_qty': -1.0, 'stock_uom': 'قطعة', 'incoming_rate': 0, 'company': 'Master Deals', 'batch_no': '', 'serial_no': None, 'project': None, 'is_cancelled': 1, 'dependant_sle_voucher_detail_no': '238598f722'}] 


[{'item_code': 'STO-ITEM-2023-00020', 'warehouse': 'المخزن الرئيسى الإسكندرية - M.D', 'posting_date': datetime.date(2023, 7, 24), 'posting_time': datetime.timedelta(seconds=25182, microseconds=908388), 'fiscal_year': '2023', 'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2023-00014', 'voucher_detail_no': '238598f722', 'actual_qty': -1.0, 'stock_uom': 'قطعة', 'incoming_rate': 0, 'company': 'Master Deals', 'batch_no': '', 'serial_no': None, 'project': None, 'is_cancelled': 0, 'dependant_sle_voucher_detail_no': '238598f722'}, {'item_code': 'STO-ITEM-2023-00020', 'warehouse': 'سامر ابراهيم صدقى نجيب - M.D', 'posting_date': datetime.date(2023, 7, 24), 'posting_time': datetime.timedelta(seconds=25182, microseconds=908388), 'fiscal_year': '2023', 'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2023-00014', 'voucher_detail_no': '238598f722', 'actual_qty': 1.0, 'stock_uom': 'قطعة', 'incoming_rate': 140.0, 'company': 'Master Deals', 'batch_no': '', 'serial_no': None, 'project': None, 'is_cancelled': 0, 'recalculate_rate': 1}]






t ={'doctype': 'Stock Entry', 'name': None, '_default_new_docs': {}, 'flags': {}, 'owner': 'Administrator', 'creation': None, 'modified': None, 'modified_by': None, 'parent': None, 'parentfield': None, 'parenttype': None, 'idx': 0, 'docstatus': 0, 'naming_series': 'MAT-STE-.YYYY.-', 'stock_entry_type': 'Material Receipt', 'outgoing_stock_entry': None, 'purpose': 'Material Issue', 'add_to_transit': 0, 'work_order': None, 'purchase_order': None, 'delivery_note_no': None, 'sales_invoice_no': None, 'pick_list': None, 'purchase_receipt_no': None, 'company': 'Master Deals', 'posting_date': '2023-07-25', 'posting_time': '09:27:39.714261', 'set_posting_time': 0, 'inspection_required': 0, 'from_bom': 0, 'apply_putaway_rule': 0, 'bom_no': None, 'fg_completed_qty': None, 'use_multi_level_bom': 1, 'from_warehouse': None, 'source_warehouse_address': None, 'source_address_display': None, 'to_warehouse': 'المخزن الرئيسى الإسكندرية - M.D', 'target_warehouse_address': None, 'target_address_display': None, 'scan_barcode': None, 'total_outgoing_value': None, 'total_incoming_value': None, 'value_difference': None, 'total_additional_costs': None, 'supplier': None, 'supplier_name': None, 'supplier_address': None, 'address_display': None, 'project': None, 'select_print_heading': None, 'letter_head': 'zxayed', 'is_opening': 'No', 'remarks': None, 'per_transferred': None, 'total_amount': None, 'job_card': None, 'amended_from': None, 'credit_note': None, 'is_return': 0, '__islocal': 1, '__unsaved': 1, 'dont_update_if_missing': [], 'items': [<StockEntryDetail: unsaved>], '_meta': <Meta: Stock Entry>} 





 [{'account': '1105 - طفايات حريق - M.D', 'against': '440001 - تسوية  مخزون - M.D', 'posting_date': '2023-07-26 08:46:06.457468', 'company': 'Master Deals', 'voucher_type': 'Real State Cost', 'voucher_no': 'MAT-LCV-2023-00027', 'fiscal_year': '2023', 'debit': 200, 'credit': 0, 'debit_in_account_currency': 200, 'credit_in_account_currency': 0, 'is_opening': 'No', 'party_type': None, 'party': None, 'cost_center': 'Main - M.D'},
   {'account': '440001 - تسوية  مخزون - M.D', 'against': '1105 - طفايات حريق - M.D', 'posting_date': '2023-07-26 08:46:06.457533', 'company': 'Master Deals', 'voucher_type': 'Real State Cost', 'voucher_no': 'MAT-LCV-2023-00027', 'fiscal_year': '2023', 'debit': 0, 'credit': 200, 'debit_in_account_currency': 0, 'credit_in_account_currency': 200, 'is_opening': 'No', 'party_type': None, 'party': None, 'cost_center': 'Main - M.D'}]